spring.application.name=uav

spring.datasource.url=jdbc:postgresql://localhost:5432/uav
spring.datasource.username=postgres
spring.datasource.password=adminA123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# solo para pruebas internas con data.sql
spring.jpa.defer-datasource-initialization=true 